In [1]:
import torch

In [2]:
import numpy as np

In [3]:
zeros_np  = np.zeros((4, 4))
ones_np   = np.ones((4, 4))
random_np = np.random.random((4, 4))

In [4]:
zeros_t  = torch.zeros(4, 4)
ones_t   = torch.ones(4, 4)
random_t = torch.rand(4, 4)

In [5]:
# Numpy -> PyTorch
tensor = torch.from_numpy(random_np)

# PyTorch -> Numpy
random_np = tensor.numpy()
#отсоединение графа градиентов
random_np = tensor.detach().numpy()

In [6]:
# Index item
print(random_np[0, 0]) # returns a float

# Index row
print(random_np[0, :]) # returns an array

0.10820612389628614
[0.10820612 0.92083275 0.85145939 0.42212981]


In [7]:
# Index item
print(random_t[0, 0]) # returns a float

# Index row
print(random_t[0, :]) # returns an array

tensor(0.2658)
tensor([0.2658, 0.6196, 0.7579, 0.5497])


In [8]:
print(random_np - ones_np)
print(random_np + ones_np)

[[-0.89179388 -0.07916725 -0.14854061 -0.57787019]
 [-0.86447017 -0.86798703 -0.28741884 -0.53677545]
 [-0.59485214 -0.6906119  -0.20254921 -0.99700485]
 [-0.42558716 -0.44669514 -0.27393629 -0.07463302]]
[[1.10820612 1.92083275 1.85145939 1.42212981]
 [1.13552983 1.13201297 1.71258116 1.46322455]
 [1.40514786 1.3093881  1.79745079 1.00299515]
 [1.57441284 1.55330486 1.72606371 1.92536698]]


In [9]:
print(random_t - ones_t)
print(random_t + ones_t)

tensor([[-0.7342, -0.3804, -0.2421, -0.4503],
        [-0.4484, -0.1205, -0.6717, -0.0604],
        [-0.9896, -0.1934, -0.6762, -0.5071],
        [-0.6581, -0.5755, -0.3359, -0.5229]])
tensor([[1.2658, 1.6196, 1.7579, 1.5497],
        [1.5516, 1.8795, 1.3283, 1.9396],
        [1.0104, 1.8066, 1.3238, 1.4929],
        [1.3419, 1.4245, 1.6641, 1.4771]])


In [10]:
print(random_np * ones_np) ##Elementwise

[[0.10820612 0.92083275 0.85145939 0.42212981]
 [0.13552983 0.13201297 0.71258116 0.46322455]
 [0.40514786 0.3093881  0.79745079 0.00299515]
 [0.57441284 0.55330486 0.72606371 0.92536698]]


In [11]:
print(random_np @ ones_np) ## Matrix

[[2.30262807 2.30262807 2.30262807 2.30262807]
 [1.44334851 1.44334851 1.44334851 1.44334851]
 [1.5149819  1.5149819  1.5149819  1.5149819 ]
 [2.77914838 2.77914838 2.77914838 2.77914838]]


In [12]:
print(random_np.shape)
print(random_np.ndim)

(4, 4)
2


In [13]:
print(random_t.shape)
print(random_t.size()) 
assert random_t.shape==random_t.size()
print(random_t.dim)

torch.Size([4, 4])
torch.Size([4, 4])
<built-in method dim of Tensor object at 0x0000027C1012E540>


In [38]:
print(random_t.size()[1])

4


In [14]:
print(random_np.shape, (random_np.reshape((8,2)).shape))

(4, 4) (8, 2)


In [15]:
print(random_t.shape, (random_t.view(8, 2).shape))

torch.Size([4, 4]) torch.Size([8, 2])


In [16]:
np.linalg.det(ones_np)

0.0

In [17]:
# pytorch doesn't have determinant function

In [18]:
print(ones_np.sum(), ones_np.mean(), ones_np.std())
print(ones_t.sum(), ones_t.mean(), ones_t.std())

16.0 1.0 0.0
tensor(16.) tensor(1.) tensor(0.)


In [19]:
print(random_np)
print(random_np.T)

[[0.10820612 0.92083275 0.85145939 0.42212981]
 [0.13552983 0.13201297 0.71258116 0.46322455]
 [0.40514786 0.3093881  0.79745079 0.00299515]
 [0.57441284 0.55330486 0.72606371 0.92536698]]
[[0.10820612 0.13552983 0.40514786 0.57441284]
 [0.92083275 0.13201297 0.3093881  0.55330486]
 [0.85145939 0.71258116 0.79745079 0.72606371]
 [0.42212981 0.46322455 0.00299515 0.92536698]]


In [20]:
print(random_t)
print(random_t.t())

tensor([[0.2658, 0.6196, 0.7579, 0.5497],
        [0.5516, 0.8795, 0.3283, 0.9396],
        [0.0104, 0.8066, 0.3238, 0.4929],
        [0.3419, 0.4245, 0.6641, 0.4771]])
tensor([[0.2658, 0.5516, 0.0104, 0.3419],
        [0.6196, 0.8795, 0.8066, 0.4245],
        [0.7579, 0.3283, 0.3238, 0.6641],
        [0.5497, 0.9396, 0.4929, 0.4771]])


In [27]:
print(torch.maximum(torch.zeros_like(random_t), random_t - 0.5))

tensor([[0.0000, 0.1196, 0.2579, 0.0497],
        [0.0516, 0.3795, 0.0000, 0.4396],
        [0.0000, 0.3066, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.1641, 0.0000]])


In [34]:
new_t = random_t - 0.5

In [35]:
new_t

tensor([[-0.2342,  0.1196,  0.2579,  0.0497],
        [ 0.0516,  0.3795, -0.1717,  0.4396],
        [-0.4896,  0.3066, -0.1762, -0.0071],
        [-0.1581, -0.0755,  0.1641, -0.0229]])

In [32]:
new_t[new_t <= 0] = 0

In [33]:
new_t

tensor([[0.0000, 0.1196, 0.2579, 0.0497],
        [0.0516, 0.3795, 0.0000, 0.4396],
        [0.0000, 0.3066, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.1641, 0.0000]])

In [36]:
2 * (random_t - 0.5)

tensor([[-0.4684,  0.2391,  0.5158,  0.0994],
        [ 0.1032,  0.7590, -0.3435,  0.8792],
        [-0.9792,  0.6132, -0.3523, -0.0143],
        [-0.3161, -0.1510,  0.3281, -0.0459]])

In [48]:
print(random_t)
torch.sum(random_t, 1, keepdims=True)

tensor([[0.2658, 0.6196, 0.7579, 0.5497],
        [0.5516, 0.8795, 0.3283, 0.9396],
        [0.0104, 0.8066, 0.3238, 0.4929],
        [0.3419, 0.4245, 0.6641, 0.4771]])


tensor([[2.1929],
        [2.6990],
        [1.6337],
        [1.9075]])

In [47]:
np.sum(random_np, axis=1, keepdims=True)

array([[2.30262807],
       [1.44334851],
       [1.5149819 ],
       [2.77914838]])